name: checkjbang

on:
  push:
    branches:
    - main
  pull_request:

jobs: 
  build:
    uses: jbanghub/.github/.github/workflows/shared-build.yml@main
    secrets: inherit
    with:
      jbang-trust-add: https://github.com/quarkiverse/quarkus-mcp-servers/
  

